//
//  BMBranding.h
//  BMWhiteLabelSDK
//
//  Created by Kevin Rejko on 1/18/16.
//  Copyright (c) 2016 Bytemark, Inc.. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface BMBranding : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* logoImageTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* logoTextTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* byteTokenLogoTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* byteTokenTextTargets;

// Drawing Methods
+ (void)drawLogoImage;
+ (void)drawLogoText;
+ (void)drawByteTokenLogo;
+ (void)drawByteTokenText;

// Generated Images
+ (UIImage*)imageOfLogoImage;
+ (UIImage*)imageOfLogoText;
+ (UIImage*)imageOfByteTokenLogo;
+ (UIImage*)imageOfByteTokenText;

@end



@interface UIColor (PaintCodeAdditions)

- (UIColor*)blendedColorWithFraction: (CGFloat)fraction ofColor: (UIColor*)color;

@end
