//
//  BMPSIcons.h
//  BMPassSDK
//
//  Created by Xiangdong Zhu on 10/23/18.
//  Copyright © 2018 Bytemark, Inc.. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//

#import <UIKit/UIKit.h>


@interface BMPSIcons : NSObject

// Drawing Methods
+ (void)drawInfoFilledWithFillColor: (UIColor*)fillColor;

// Generated Images
+ (UIImage*)imageOfInfoFilledWithFillColor: (UIColor*)fillColor;

@end
