//
//  BMSocialIcons.h
//  BMWhiteLabelSDK
//
//  Created by Apoorva Reed on 3/24/20.
//  Copyright © 2020 Bytemark, Inc.. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//

#import <UIKit/UIKit.h>



typedef NS_ENUM(NSInteger, BMSocialIconsResizingBehavior)
{
    BMSocialIconsResizingBehaviorAspectFit, //!< The content is proportionally resized to fit into the target rectangle.
    BMSocialIconsResizingBehaviorAspectFill, //!< The content is proportionally resized to completely fill the target rectangle.
    BMSocialIconsResizingBehaviorStretch, //!< The content is stretched to match the entire target rectangle.
    BMSocialIconsResizingBehaviorCenter, //!< The content is centered in the target rectangle, but it is NOT resized.

};

extern CGRect BMSocialIconsResizingBehaviorApply(BMSocialIconsResizingBehavior behavior, CGRect rect, CGRect target);


@interface BMSocialIcons : NSObject

// iOS Controls Customization Outlets
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* fbTargets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* googleTargets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* fbSquareTargets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* gTargets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* appleSquareTargets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* google_newTargets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* fb_newTargets;

// Generated Images
+ (UIImage*)imageOfFb;
+ (UIImage*)imageOfGoogle;
+ (UIImage*)imageOfFbSquare;
+ (UIImage*)imageOfG;
+ (UIImage*)imageOfAppleSquare;
+ (UIImage*)imageOfGoogle_new;
+ (UIImage*)imageOfFb_new;

@end
