//
//  BMActivityMessageIcons.h
//  BMWhiteLabel
//
//  Created by Kevin Rejko on 11/7/14.
//  Copyright (c) 2014 Bytemark, Inc.. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface BMActivityMessageIcons : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* checkTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* crossTargets;

// Generated Images
+ (UIImage*)imageOfCheck;
+ (UIImage*)imageOfCross;

@end
