//
//  BMCards.h
//  BMWhiteLabelSDK
//
//  Created by Kevin Rejko on 20/07/20.
//  Copyright © 2020 Bytemark, Inc.. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//

#import <UIKit/UIKit.h>



@interface UIColor (BMCardsAdditions)

- (UIColor*)blendedColorWithFraction: (CGFloat)fraction ofColor: (UIColor*)color;

@end



typedef NS_ENUM(NSInteger, BMCardsResizingBehavior)
{
    BMCardsResizingBehaviorAspectFit, //!< The content is proportionally resized to fit into the target rectangle.
    BMCardsResizingBehaviorAspectFill, //!< The content is proportionally resized to completely fill the target rectangle.
    BMCardsResizingBehaviorStretch, //!< The content is stretched to match the entire target rectangle.
    BMCardsResizingBehaviorCenter, //!< The content is centered in the target rectangle, but it is NOT resized.

};

extern CGRect BMCardsResizingBehaviorApply(BMCardsResizingBehavior behavior, CGRect rect, CGRect target);


@interface BMCards : NSObject

// iOS Controls Customization Outlets
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* amexTargets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* bankTargets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* cirrusTargets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* dinerClubTargets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* discoverTargets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* genericTargets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* jBCTargets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* masteroTargets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* masterCardTargets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* soloTargets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* unionPayTargets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* visaTargets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* visaBlueTargets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* payPalTargets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* payNearMeTargets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* dotpayTargets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* storedWalletMethodTargets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* walletnewCanvasTargets;

// Drawing Methods
+ (void)drawAmex;
+ (void)drawBank;
+ (void)drawCirrus;
+ (void)drawDinerClub;
+ (void)drawDiscover;
+ (void)drawGeneric;
+ (void)drawJBC;
+ (void)drawMastero;
+ (void)drawMasterCard;
+ (void)drawSolo;
+ (void)drawUnionPay;
+ (void)drawVisa;
+ (void)drawVisaBlue;
+ (void)drawSplitPaymentWithCardColor: (UIColor*)cardColor;
+ (void)drawAddCardWithCardColor: (UIColor*)cardColor;
+ (void)drawSinglePaymentWithCardColor: (UIColor*)cardColor;
+ (void)drawPayPal;
+ (void)drawPayNearMe;
+ (void)drawDotpay;
+ (void)drawStoredWalletMethod;
+ (void)drawStoredWalletMethodWithFrame: (CGRect)targetFrame resizing: (BMCardsResizingBehavior)resizing;
+ (void)drawWalletnewCanvas;
+ (void)drawWalletnewCanvasWithFrame: (CGRect)targetFrame resizing: (BMCardsResizingBehavior)resizing;
+ (void)drawIncomm;
+ (void)drawIncommWithFrame: (CGRect)targetFrame resizing: (BMCardsResizingBehavior)resizing;

// Generated Images
+ (UIImage*)imageOfAmex;
+ (UIImage*)imageOfBank;
+ (UIImage*)imageOfCirrus;
+ (UIImage*)imageOfDinerClub;
+ (UIImage*)imageOfDiscover;
+ (UIImage*)imageOfGeneric;
+ (UIImage*)imageOfJBC;
+ (UIImage*)imageOfMastero;
+ (UIImage*)imageOfMasterCard;
+ (UIImage*)imageOfSolo;
+ (UIImage*)imageOfUnionPay;
+ (UIImage*)imageOfVisa;
+ (UIImage*)imageOfVisaBlue;
+ (UIImage*)imageOfSplitPaymentWithCardColor: (UIColor*)cardColor;
+ (UIImage*)imageOfAddCardWithCardColor: (UIColor*)cardColor;
+ (UIImage*)imageOfSinglePaymentWithCardColor: (UIColor*)cardColor;
+ (UIImage*)imageOfPayPal;
+ (UIImage*)imageOfPayNearMe;
+ (UIImage*)imageOfIncomm;
+ (UIImage*)imageOfDotpay;
+ (UIImage*)imageOfStoredWalletMethod;
+ (UIImage*)imageOfWalletnewCanvas;

@end
