//
//  ErrorDefines.h
//  BMPassSDK
//
//  Created by Kevin Rejko on 5/23/13.
//  Copyright (c) 2013 Bytemark. All rights reserved.
//

#ifndef BMPassSDK_ErrorDefines_h
#define BMPassSDK_ErrorDefines_h

#define kSDK_NOT_INITIALIZED_CODE 100
#define kAPI_ERROR_CODE 101
#define kUNEXPECTED_ERROR_CODE 102
#define kUNABLE_TO_DISPLAY_CODE 103
#define kNO_PASS_SPECIFIED_CODE 104
#define kUSER_CANCELLED_CODE 105
#define kNOT_AUTHENTICATED_CODE 106
#define kNETWORK_NOT_AVAILABLE_CODE 107
#define kORDER_NOT_VALID_CODE 108
#define kDUPLICATE_PASSES_CODE 109
#define kPARAMETERS_INVALID_CODE 110
#define kEVENT_EXPIRED_CODE 111
#define kPASS_NOT_FOUND_CODE 112
#define kPASS_EXPIRED_CODE 113
#define kPASS_USES_GONE_CODE 114
#define kPASS_UNAVAILABLE_CODE 115
#define kPASS_NOT_STACKABLE_CODE 116
#define kINVALID_API_RESPONSE_CODE 117
#define kSDK_FEATURE_NOT_AVAILABLE_CODE 118
#define kNO_EVENT_SPECIFIED_CODE 119
#define kINVALID_TIME_CODE 120
#define kMISSING_PASS_ENABLER_CODE 121
#define kINVALID_RESTRICTIONS_CODE 122
#define kCACHE_EXPIRED_CODE 123
#define kMISSING_DAIU_CODE 124
#define kUNRESOLVED_DEPENDENCY_CODE 125
#define kINVALID_INPUT_CODE 127
#define kAPPLE_PAY_FAIL_CODE 128
#define kSERVER_APPLICATION_ERROR_CODE 500
#define kKEY_USER_CANCELLED_GOOGLE_SIGN_IN_CODE -5

#endif
