//
//  BMIndicators.h
//  BMWhiteLabelSDK
//
//  Created by Chandan Kumar on 18/03/21.
//  Copyright © 2021 Bytemark, Inc.. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//

#import <UIKit/UIKit.h>



typedef NS_ENUM(NSInteger, BMIndicatorsResizingBehavior)
{
    BMIndicatorsResizingBehaviorAspectFit, //!< The content is proportionally resized to fit into the target rectangle.
    BMIndicatorsResizingBehaviorAspectFill, //!< The content is proportionally resized to completely fill the target rectangle.
    BMIndicatorsResizingBehaviorStretch, //!< The content is stretched to match the entire target rectangle.
    BMIndicatorsResizingBehaviorCenter, //!< The content is centered in the target rectangle, but it is NOT resized.

};

extern CGRect BMIndicatorsResizingBehaviorApply(BMIndicatorsResizingBehavior behavior, CGRect rect, CGRect target);


@interface BMIndicators : NSObject

// Drawing Methods
+ (void)drawCartEmptyWithFrame: (CGRect)frame color: (UIColor*)color;
+ (void)drawCheckSuccessWithFrame: (CGRect)frame color: (UIColor*)color;
+ (void)drawEmptyStateWithFrame: (CGRect)frame color: (UIColor*)color;
+ (void)drawErrorWithFrame: (CGRect)frame color: (UIColor*)color;
+ (void)drawPaymentMethodEmptyWithFrame: (CGRect)frame color: (UIColor*)color;
+ (void)drawSignInWithFrame: (CGRect)frame color: (UIColor*)color;
+ (void)drawTicketsEmptyWithFrame: (CGRect)frame color: (UIColor*)color;
+ (void)drawCheckWithFrame: (CGRect)frame color: (UIColor*)color;
+ (void)drawStoreLoadingWithFrame: (CGRect)frame color: (UIColor*)color;
+ (void)drawStoreWithFrame: (CGRect)frame color: (UIColor*)color;
+ (void)drawPlaceOrderTicketWithFrame: (CGRect)frame color: (UIColor*)color;
+ (void)drawPaymentsWithFrame: (CGRect)frame color: (UIColor*)color;
+ (void)drawFareCappingWithFrame: (CGRect)frame color: (UIColor*)color;
+ (void)drawCheckmarkWithFrame: (CGRect)frame color: (UIColor*)color;
+ (void)drawInfoBarIconWithColor: (UIColor*)color;
+ (void)drawInfoBarIconWithFrame: (CGRect)targetFrame resizing: (BMIndicatorsResizingBehavior)resizing color: (UIColor*)color;
+ (void)drawDropdownFilledWithColor: (UIColor*)color;
+ (void)drawDropdownFilledWithFrame: (CGRect)targetFrame resizing: (BMIndicatorsResizingBehavior)resizing color: (UIColor*)color;
+ (void)drawSwapIconWithColor: (UIColor*)color;
+ (void)drawSwapIconWithFrame: (CGRect)targetFrame resizing: (BMIndicatorsResizingBehavior)resizing color: (UIColor*)color;
+ (void)drawNotificationsWithFrame: (CGRect)frame color: (UIColor*)color;
+ (void)drawOriginDestinationWithFrame: (CGRect)frame color: (UIColor*)color;
+ (void)drawSlidersWithFrame: (CGRect)frame color: (UIColor*)color;
+ (void)drawChevronLeftWithLockCircleColor: (UIColor*)lockCircleColor;
+ (void)drawChevronLeftWithFrame: (CGRect)targetFrame resizing: (BMIndicatorsResizingBehavior)resizing lockCircleColor: (UIColor*)lockCircleColor;
+ (void)drawChevronRightWithLockCircleColor: (UIColor*)lockCircleColor;
+ (void)drawChevronUpWithLockCircleColor: (UIColor*)lockCircleColor;
+ (void)drawChevronDownWithLockCircleColor: (UIColor*)lockCircleColor;
+ (void)drawArrowLeftWithLockCircleColor: (UIColor*)lockCircleColor;
+ (void)drawArrowLeftWithFrame: (CGRect)targetFrame resizing: (BMIndicatorsResizingBehavior)resizing lockCircleColor: (UIColor*)lockCircleColor;
+ (void)drawArrowRightWithLockCircleColor: (UIColor*)lockCircleColor;
+ (void)drawArrowUpWithLockCircleColor: (UIColor*)lockCircleColor;
+ (void)drawArrowDownWithLockCircleColor: (UIColor*)lockCircleColor;
+ (void)drawStartingPositionWithPrimaryColor: (UIColor*)primaryColor;
+ (void)drawMiddlePositionWithPrimaryColor: (UIColor*)primaryColor secondaryColor: (UIColor*)secondaryColor;
+ (void)drawEndingPositionWithPrimaryColor: (UIColor*)primaryColor;
+ (void)drawExpirationWithFrame: (CGRect)targetFrame color: (UIColor*)color;

// Generated Images
+ (UIImage*)imageOfCartEmptyWithSize: (CGSize)imageSize color: (UIColor*)color;
+ (UIImage*)imageOfCheckSuccessWithSize: (CGSize)imageSize color: (UIColor*)color;
+ (UIImage*)imageOfEmptyStateWithSize: (CGSize)imageSize color: (UIColor*)color;
+ (UIImage*)imageOfErrorWithSize: (CGSize)imageSize color: (UIColor*)color;
+ (UIImage*)imageOfPaymentMethodEmptyWithSize: (CGSize)imageSize color: (UIColor*)color;
+ (UIImage*)imageOfSignInWithSize: (CGSize)imageSize color: (UIColor*)color;
+ (UIImage*)imageOfTicketsEmptyWithSize: (CGSize)imageSize color: (UIColor*)color;
+ (UIImage*)imageOfCheckWithSize: (CGSize)imageSize color: (UIColor*)color;
+ (UIImage*)imageOfStoreLoadingWithSize: (CGSize)imageSize color: (UIColor*)color;
+ (UIImage*)imageOfCommuterBenefitsCard:(CGSize)imageSize;
+ (UIImage*)imageOfStoreWithSize: (CGSize)imageSize color: (UIColor*)color;
+ (UIImage*)imageOfPlaceOrderTicketWithSize: (CGSize)imageSize color: (UIColor*)color;
+ (UIImage*)imageOfPaymentsWithSize: (CGSize)imageSize color: (UIColor*)color;
+ (UIImage*)imageOfFareCappingWithSize: (CGSize)imageSize color: (UIColor*)color;
+ (UIImage*)imageOfCheckmarkWithSize: (CGSize)imageSize color: (UIColor*)color;
+ (UIImage*)imageOfInfoBarIconWithColor: (UIColor*)color;
+ (UIImage*)imageOfDropdownFilledWithColor: (UIColor*)color;
+ (UIImage*)imageOfSwapIconWithColor: (UIColor*)color;
+ (UIImage*)imageOfNotificationsWithSize: (CGSize)imageSize color: (UIColor*)color;
+ (UIImage*)imageOfOriginDestinationWithSize: (CGSize)imageSize color: (UIColor*)color;
+ (UIImage*)imageOfSlidersWithSize: (CGSize)imageSize color: (UIColor*)color;
+ (UIImage*)imageOfChevronLeftWithLockCircleColor: (UIColor*)lockCircleColor;
+ (UIImage*)imageOfChevronRightWithLockCircleColor: (UIColor*)lockCircleColor;
+ (UIImage*)imageOfChevronUpWithLockCircleColor: (UIColor*)lockCircleColor;
+ (UIImage*)imageOfChevronDownWithLockCircleColor: (UIColor*)lockCircleColor;
+ (UIImage*)imageOfArrowLeftWithLockCircleColor: (UIColor*)lockCircleColor;
+ (UIImage*)imageOfArrowRightWithLockCircleColor: (UIColor*)lockCircleColor;
+ (UIImage*)imageOfArrowUpWithLockCircleColor: (UIColor*)lockCircleColor;
+ (UIImage*)imageOfArrowDownWithLockCircleColor: (UIColor*)lockCircleColor;
+ (UIImage*)imageOfStartingPositionWithPrimaryColor: (UIColor*)primaryColor;
+ (UIImage*)imageOfMiddlePositionWithPrimaryColor: (UIColor*)primaryColor secondaryColor: (UIColor*)secondaryColor;
+ (UIImage*)imageOfEndingPositionWithPrimaryColor: (UIColor*)primaryColor;
+ (UIImage*)imageOfPassengerWithSize: (CGSize)imageSize color: (UIColor*)color;
+ (UIImage*)imageOfExpirationWithSize: (CGSize)imageSize color: (UIColor*)color;
+ (UIImage*)imageOfUnionCanvasWithSize: (CGSize)imageSize color: (UIColor*)color;

@end
