#if 0
#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 6.1 effective-5.10 (swiftlang-6.1.0.110.21 clang-1700.0.13.3)
#ifndef BMTCORESDK_SWIFT_H
#define BMTCORESDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreData;
@import CoreFoundation;
@import Foundation;
@import MessageUI;
@import ObjectiveC;
@import UIKit;
@import WebKit;
#endif

#import <BMTCoreSDK/BMTCoreSDK.h>

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="BMTCoreSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSEntityDescription;
@class NSManagedObjectContext;
SWIFT_CLASS_NAMED("AppIDStorage")
@interface AppIDStorage : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@class NSObject;
@interface AppIDStorage (SWIFT_EXTENSION(BMTCoreSDK))
@property (nonatomic, strong) NSObject * _Nullable key;
@end

@class NSString;
SWIFT_CLASS("_TtC10BMTCoreSDK20BMActionSheetUtility")
@interface BMActionSheetUtility : NSObject
+ (void)presentActionSheetWithTitle:(NSString * _Nullable)title message:(NSString * _Nullable)message cancelTitle:(NSString * _Nullable)cancelTitle actions:(NSArray<NSString *> * _Nonnull)actions buttonHiddenStatus:(NSArray<NSNumber *> * _Nonnull)buttonHiddenStatus completion:(void (^ _Nonnull)(NSInteger))completion;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC10BMTCoreSDK9BMLogging")
@interface BMLogging : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSURL;
@class NSURLRequest;
SWIFT_CLASS("_TtC10BMTCoreSDK23BMNetworkRequestBuilder")
@interface BMNetworkRequestBuilder : NSObject
- (nonnull instancetype)initWithUrl:(NSURL * _Nullable)url baseURL:(NSURL * _Nonnull)baseURL path:(NSString * _Nonnull)path method:(NSString * _Nonnull)method parameters:(NSDictionary<NSString *, id> * _Nullable)parameters headers:(NSDictionary<NSString *, NSString *> * _Nullable)headers handleWeakConnectivity:(BOOL)handleWeakConnectivity OBJC_DESIGNATED_INITIALIZER;
- (NSURLRequest * _Nullable)buildURLRequest SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class BMSessionCache;
SWIFT_CLASS("_TtC10BMTCoreSDK23BMNotificationRetriever")
@interface BMNotificationRetriever : BMLiveUpdateRetriever
- (NSString * _Nullable)updateNotificationName SWIFT_WARN_UNUSED_RESULT;
- (BMSessionCache * _Nullable)cache SWIFT_WARN_UNUSED_RESULT;
- (void)callbackLocalData:(NSArray * _Nullable)data errors:(NSArray * _Nullable)errors;
- (void)callbackRemoteData:(NSArray * _Nullable)data errors:(NSArray * _Nullable)errors;
- (void)callbackChangedLoading:(BOOL)isLoading;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIImage;
SWIFT_CLASS("_TtC10BMTCoreSDK24BMPSImageDownloadManager")
@interface BMPSImageDownloadManager : NSObject
- (void)fetchImageWithURLString:(NSString * _Nonnull)imageURLString completion:(void (^ _Nonnull)(UIImage * _Nullable))completion;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC10BMTCoreSDK29BMPSOrganizationConfiguration")
@interface BMPSOrganizationConfiguration : NSObject
+ (NSString * _Nonnull)getMaxValueForINCOMM SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getMinValueForINCOMM SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)isTransferCardEnabled SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)isAddCreditCardAlertEnabled SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)isMultiAgencySystem SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)isShowAgencyLongNameOnSelection SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)isPaymentCheckRequired SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)showSelectPaymentMethodFallback SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getEncryptedPayloadExpiration SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)isNMIEnabled SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)isAppleEnabledForStoreScreen SWIFT_WARN_UNUSED_RESULT;
+ (void)setApplePayMerchantIDForParentLevelWithValue:(NSString * _Nonnull)value;
+ (NSString * _Nonnull)getApplePayMerchantIDForParentLevel SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)isAppRatingDisabled SWIFT_WARN_UNUSED_RESULT;
+ (NSInteger)getAllowedCardTrasnferCount SWIFT_WARN_UNUSED_RESULT;
+ (NSInteger)getAllowedCardTrasnferDaysInterval SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)isTransferRestrictionEnabled SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)hideCreateIfTransferableCardAvailable SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)isFareCategorySelectionDisabled SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)isRemoveVirtualCardEnabled SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)passAutoRenewalWithWalletnCashEnabled SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)showTimeSyncAlert SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)is2FAEnabled SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)showCommuterBenifitCardAllowed SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)upassVerificationCodeRequired SWIFT_WARN_UNUSED_RESULT;
+ (void)setUseCustomInAppMessageUIWithValue:(BOOL)value;
+ (BOOL)useCustomInAppMessageUI SWIFT_WARN_UNUSED_RESULT;
+ (void)setIsHybridAppWithEnabled:(BOOL)enabled;
+ (BOOL)isHybridApp SWIFT_WARN_UNUSED_RESULT;
+ (void)setLinkExistingCardSectionWithEnabled:(BOOL)enabled;
+ (void)setIsOpenLoopWithEnabled:(BOOL)enabled;
+ (BOOL)isOpenLoopEnabled SWIFT_WARN_UNUSED_RESULT;
+ (void)setHideCreateVirtualCardKeyWithValue:(BOOL)value;
+ (BOOL)hideCreateVirtualCard SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UILabel;
@class NSCoder;
SWIFT_CLASS("_TtC10BMTCoreSDK20BMPaymentProductView")
@interface BMPaymentProductView : UIView
@property (nonatomic, readonly, strong) UILabel * _Nonnull quantityLabel;
@property (nonatomic, readonly, strong) UILabel * _Nonnull nameLabel;
@property (nonatomic, readonly, strong) UILabel * _Nonnull productCostLabel;
@property (nonatomic, readonly, strong) UILabel * _Nonnull originDestinationLabel;
@property (nonatomic, readonly, strong) UILabel * _Nonnull subscriptionLabel;
@property (nonatomic, readonly, strong) UILabel * _Nonnull parkingDetailsLabel;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class BTMKOrganization;
@interface BMPaymentProductView (SWIFT_EXTENSION(BMTCoreSDK)) <BTMKThemeDelegate>
- (void)applyThemeFromOrganization:(BTMKOrganization * _Null_unspecified)organization;
@end

SWIFT_CLASS("_TtC10BMTCoreSDK19BMTAnalyticsHandler")
@interface BMTAnalyticsHandler : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) void (^ _Nullable logContentViewClosure)(NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull, NSDictionary<NSString *, id> * _Nonnull);)
+ (void (^ _Nullable)(NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull, NSDictionary<NSString *, id> * _Nonnull))logContentViewClosure SWIFT_WARN_UNUSED_RESULT;
+ (void)setLogContentViewClosure:(void (^ _Nullable)(NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull, NSDictionary<NSString *, id> * _Nonnull))value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) void (^ _Nullable logCustomEventClosure)(NSString * _Nonnull, NSDictionary<NSString *, id> * _Nonnull);)
+ (void (^ _Nullable)(NSString * _Nonnull, NSDictionary<NSString *, id> * _Nonnull))logCustomEventClosure SWIFT_WARN_UNUSED_RESULT;
+ (void)setLogCustomEventClosure:(void (^ _Nullable)(NSString * _Nonnull, NSDictionary<NSString *, id> * _Nonnull))value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) void (^ _Nullable reportLoginStatusClosure)(NSString * _Nonnull);)
+ (void (^ _Nullable)(NSString * _Nonnull))reportLoginStatusClosure SWIFT_WARN_UNUSED_RESULT;
+ (void)setReportLoginStatusClosure:(void (^ _Nullable)(NSString * _Nonnull))value;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC10BMTCoreSDK21BMTCoreSDKInitializer")
@interface BMTCoreSDKInitializer : NSObject <BMInitializer>
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) BMTCoreSDKInitializer * _Nonnull sharedInitializer;)
+ (BMTCoreSDKInitializer * _Nonnull)sharedInitializer SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
+ (BOOL)isInitialized SWIFT_WARN_UNUSED_RESULT;
- (void)configureWithDictionary:(NSDictionary * _Null_unspecified)dictionary;
- (void)deleteLocalDataBase;
@end

@class NSDate;
enum DateFormat : NSInteger;
@class NSDateComponents;
SWIFT_CLASS("_TtC10BMTCoreSDK14BMTDateUtility")
@interface BMTDateUtility : NSObject
+ (NSString * _Nonnull)getAndFormatDateWithDate:(NSDate * _Nonnull)date format:(enum DateFormat)format SWIFT_WARN_UNUSED_RESULT;
+ (NSDateComponents * _Nonnull)todayComponents SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)isValidDateWithMonth:(NSString * _Nonnull)month year:(NSString * _Nonnull)year SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)detectDateFormatAndValidity:(NSString * _Nonnull)dateString SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC10BMTCoreSDK16BMUUIDIdentifier")
@interface BMUUIDIdentifier : NSObject
+ (NSString * _Nonnull)applicationInstallationIdentifier SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC10BMTCoreSDK28BMWLButtonTextWithArrowImage")
@interface BMWLButtonTextWithArrowImage : UIButton
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithTitle:(NSString * _Nonnull)title;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@end

SWIFT_CLASS("_TtC10BMTCoreSDK26BMWLChangeAgencyHeaderView")
@interface BMWLChangeAgencyHeaderView : UIView
@property (nonatomic, readonly, strong) UILabel * _Nonnull orgLabel;
@property (nonatomic, readonly, strong) UIButton * _Nonnull changeAgencyButton;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
- (void)setEmpty;
@end

@class WKWebView;
@class NSBundle;
SWIFT_CLASS("_TtC10BMTCoreSDK19BMWebViewController")
@interface BMWebViewController : BMViewController
@property (nonatomic, copy) NSString * _Nullable urlString;
@property (nonatomic, copy) NSString * _Nullable navTitle;
@property (nonatomic, strong) WKWebView * _Nullable webView;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)loadView;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
@end

SWIFT_CLASS("_TtC10BMTCoreSDK29BMWLDeepLinkWebViewController")
@interface BMWLDeepLinkWebViewController : BMWebViewController
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@interface BMWLDeepLinkWebViewController (SWIFT_EXTENSION(BMTCoreSDK)) <BMInternetConnectionStatusChangedDelegate>
- (void)internetConnectionGained;
@end

@class WKNavigationAction;
@class WKWebViewConfiguration;
@class WKWindowFeatures;
@class WKNavigation;
@interface BMWLDeepLinkWebViewController (SWIFT_EXTENSION(BMTCoreSDK))
- (void)webView:(WKWebView * _Nonnull)webView decidePolicyForNavigationAction:(WKNavigationAction * _Nonnull)navigationAction decisionHandler:(void (^ _Nonnull)(WKNavigationActionPolicy))decisionHandler;
- (WKWebView * _Nullable)webView:(WKWebView * _Nonnull)webView createWebViewWith:(WKWebViewConfiguration * _Nonnull)configuration for:(WKNavigationAction * _Nonnull)navigationAction windowFeatures:(WKWindowFeatures * _Nonnull)windowFeatures SWIFT_WARN_UNUSED_RESULT;
- (void)webView:(WKWebView * _Nonnull)webView didReceiveServerRedirectForProvisionalNavigation:(WKNavigation * _Null_unspecified)navigation;
@end

SWIFT_CLASS("_TtC10BMTCoreSDK27BMWLDropdownUnderlineButton")
@interface BMWLDropdownUnderlineButton : UIButton
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIColor;
@class UIFont;
SWIFT_CLASS("_TtC10BMTCoreSDK21BMWLFloatingTextField")
@interface BMWLFloatingTextField : UITextField
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)BMWL_editingChanged;
@property (nonatomic, strong) UILabel * _Nullable titleLabel;
@property (nonatomic, strong) UIView * _Nullable lineView;
@property (nonatomic, strong) UILabel * _Nullable errorLabel;
@property (nonatomic) NSTimeInterval titleFadeInDuration;
@property (nonatomic) NSTimeInterval titleFadeOutDuration;
@property (nonatomic, copy) BOOL (^ _Nullable textFieldShouldChangeCharactersBlock)(UITextField * _Nullable, NSRange, NSString * _Nullable);
@property (nonatomic, strong) UIColor * _Nullable textColor;
@property (nonatomic, strong) UIColor * _Nonnull placeholderColor;
@property (nonatomic, strong) UIFont * _Nullable placeholderFont;
@property (nonatomic, strong) UIColor * _Nonnull titleColor;
@property (nonatomic, strong) UIColor * _Nonnull selectedTitleColor;
@property (nonatomic, strong) UIColor * _Nonnull lineColor;
@property (nonatomic, strong) UIColor * _Nonnull selectedLineColor;
@property (nonatomic, strong) UIColor * _Nonnull errorColor;
@property (nonatomic) CGFloat lineHeight;
@property (nonatomic) CGFloat selectedLineHeight;
@property (nonatomic, getter=isSecureTextEntry) BOOL secureTextEntry;
@property (nonatomic, copy) NSString * _Nullable error;
@property (nonatomic, readonly) BOOL editingOrSelected;
@property (nonatomic, readonly) BOOL hasError;
@property (nonatomic, copy) NSString * _Nullable text;
@property (nonatomic, copy) NSString * _Nullable placeholder;
@property (nonatomic, copy) NSString * _Nullable topTitle;
@property (nonatomic, copy) NSString * _Nullable selectedTitle;
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, getter=isSelected) BOOL selected;
- (BOOL)becomeFirstResponder SWIFT_WARN_UNUSED_RESULT;
- (BOOL)resignFirstResponder SWIFT_WARN_UNUSED_RESULT;
- (void)updateColors;
- (void)placeHolderUpdatedWithMandatoryWithPlaceholder:(NSString * _Nonnull)placeholder isRequired:(BOOL)isRequired;
- (void)configureTextFieldWithTopTitle:(NSString * _Nonnull)topTitle placeholder:(NSString * _Nonnull)placeholder isRequired:(BOOL)isRequired;
- (void)setTitleVisible:(BOOL)titleVisible animated:(BOOL)animated animationCompletion:(void (^ _Nullable)(void))animationCompletion;
- (BOOL)isTitleVisible SWIFT_WARN_UNUSED_RESULT;
- (CGRect)textRectForBounds:(CGRect)bounds SWIFT_WARN_UNUSED_RESULT;
- (CGRect)editingRectForBounds:(CGRect)bounds SWIFT_WARN_UNUSED_RESULT;
- (CGRect)placeholderRectForBounds:(CGRect)bounds SWIFT_WARN_UNUSED_RESULT;
- (CGRect)rightViewRectForBounds:(CGRect)bounds SWIFT_WARN_UNUSED_RESULT;
- (CGRect)clearButtonRectForBounds:(CGRect)bounds SWIFT_WARN_UNUSED_RESULT;
- (CGRect)titleLabelRectForBounds:(CGRect)bounds editing:(BOOL)editing SWIFT_WARN_UNUSED_RESULT;
- (CGRect)lineViewRectForBounds:(CGRect)bounds editing:(BOOL)editing SWIFT_WARN_UNUSED_RESULT;
- (CGRect)errorLabelRectForBounds:(CGRect)bounds SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)titleHeight SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)textHeight SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)errorHeight SWIFT_WARN_UNUSED_RESULT;
- (void)prepareForInterfaceBuilder;
- (void)layoutSubviews;
@property (nonatomic, readonly) CGSize intrinsicContentSize;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (void)applyThemeFromOrganizationWithOrganization:(BTMKOrganization * _Nonnull)organization;
@end

SWIFT_CLASS("_TtC10BMTCoreSDK10BMWLImages")
@interface BMWLImages : NSObject
+ (UIImage * _Nonnull)imageOfCrossWithColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
+ (void)drawCrossWithPrimaryColorWithPrimaryColor:(UIColor * _Nonnull)primaryColor;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIViewController;
SWIFT_CLASS("_TtC10BMTCoreSDK29BMWLMailComposeViewController")
@interface BMWLMailComposeViewController : MFMailComposeViewController <MFMailComposeViewControllerDelegate>
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
- (void)mailComposeController:(MFMailComposeViewController * _Nonnull)controller didFinishWithResult:(MFMailComposeResult)result error:(NSError * _Nullable)error;
- (nonnull instancetype)initWithNavigationBarClass:(Class _Nullable)navigationBarClass toolbarClass:(Class _Nullable)toolbarClass SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithRootViewController:(UIViewController * _Nonnull)rootViewController SWIFT_UNAVAILABLE;
@end

@class BMNotification;
@class NSNumber;
SWIFT_CLASS("_TtC10BMTCoreSDK25BMWLNotificationViewModel")
@interface BMWLNotificationViewModel : NSObject
@property (nonatomic, copy) NSString * _Nullable shortMessage;
@property (nonatomic, copy) NSString * _Nullable message;
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, copy) NSString * _Nullable urlString;
@property (nonatomic, readonly, copy) NSString * _Nullable uuid;
@property (nonatomic, strong) BMNotification * _Nullable model;
@property (nonatomic, strong) NSNumber * _Nullable hasBeenSeen;
- (nonnull instancetype)initWithModel:(BMNotification * _Nonnull)model OBJC_DESIGNATED_INITIALIZER;
- (BOOL)shouldOpenURL SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC10BMTCoreSDK34BMWLNotificationsWebViewController")
@interface BMWLNotificationsWebViewController : BMWebViewController
- (nonnull instancetype)initWithNotification:(BMWLNotificationViewModel * _Nullable)notification OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end

SWIFT_CLASS("_TtC10BMTCoreSDK12BMWLOrgModel")
@interface BMWLOrgModel : NSSecureUnarchiveFromDataTransformer <NSCoding>
@property (nonatomic, copy) NSString * _Nullable legacyUUID;
@property (nonatomic, copy) NSString * _Nullable fullName;
@property (nonatomic, copy) NSString * _Nullable imagePath;
@property (nonatomic, copy) NSString * _Nullable location;
@property (nonatomic, copy) NSString * _Nullable systemSource;
@property (nonatomic, copy) NSString * _Nullable baseURL;
@property (nonatomic, copy) NSString * _Nullable organizationUUID;
@property (nonatomic, copy) NSString * _Nullable shortName;
@property (nonatomic, readonly, copy) NSString * _Nonnull orgName;
- (void)encodeWithCoder:(NSCoder * _Nonnull)coder;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface BMWebViewController (SWIFT_EXTENSION(BMTCoreSDK)) <WKNavigationDelegate>
- (void)webView:(WKWebView * _Nonnull)webView decidePolicyForNavigationAction:(WKNavigationAction * _Nonnull)navigationAction decisionHandler:(void (^ _Nonnull)(WKNavigationActionPolicy))decisionHandler;
- (void)webView:(WKWebView * _Nonnull)webView didStartProvisionalNavigation:(WKNavigation * _Null_unspecified)navigation;
- (void)webView:(WKWebView * _Nonnull)webView didFinishNavigation:(WKNavigation * _Null_unspecified)navigation;
- (void)webView:(WKWebView * _Nonnull)webView didFailNavigation:(WKNavigation * _Null_unspecified)navigation withError:(NSError * _Nonnull)error;
@end

@class BTMKMenuItemAction;
SWIFT_CLASS("_TtC10BMTCoreSDK12BTMKMenuItem")
@interface BTMKMenuItem : NSObject
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, copy) NSString * _Nullable screenTitle;
@property (nonatomic, copy) NSString * _Nullable subtitle;
@property (nonatomic, copy) NSString * _Nullable selectedImageName;
@property (nonatomic, copy) NSString * _Nullable unselectedImageName;
@property (nonatomic, strong) BTMKMenuItemAction * _Nullable action;
@property (nonatomic) BOOL isHaconScreen;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)performActionWithSender:(id _Nonnull)sender;
@end

SWIFT_CLASS("_TtC10BMTCoreSDK18BTMKMenuItemAction")
@interface BTMKMenuItemAction : NSObject
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic) id _Nullable context;
@property (nonatomic, copy) NSDictionary * _Nullable additionalInfo;
@property (nonatomic, copy) void (^ _Nullable callback)(void);
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (BOOL)performActionWithSender:(id _Nonnull)sender withTitle:(NSString * _Nullable)title SWIFT_WARN_UNUSED_RESULT;
- (BOOL)performActionWithSender:(id _Nonnull)sender withTitle:(NSString * _Nullable)title userInfo:(id _Nullable)userInfo SWIFT_WARN_UNUSED_RESULT;
@end

SWIFT_CLASS_NAMED("CNotification")
@interface CNotification : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@interface CNotification (SWIFT_EXTENSION(BMTCoreSDK))
@property (nonatomic, strong) NSObject * _Nullable key;
@end

@class NSTimer;
SWIFT_CLASS("_TtC10BMTCoreSDK15CaptureDetector")
@interface CaptureDetector : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) CaptureDetector * _Nonnull shared;)
+ (CaptureDetector * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull kCaptureStatusChangedNotification;)
+ (NSString * _Nonnull)kCaptureStatusChangedNotification SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (BOOL)isCapturing SWIFT_WARN_UNUSED_RESULT;
+ (void)triggerDetectorTimer;
- (void)checkCurrentCapturingStatus:(NSTimer * _Nullable)timer;
+ (void)stopDetectorTimer;
+ (void)hideScreenWhenCaptures;
@end

SWIFT_CLASS("_TtC10BMTCoreSDK21CapturePreventingView")
@interface CapturePreventingView : UIView
@property (nonatomic) BOOL preventScreenCapture;
- (nonnull instancetype)initWithContentView:(UIView * _Nullable)contentView OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (void)setupWithContentView:(UIView * _Nonnull)contentView;
@end

SWIFT_CLASS("_TtC10BMTCoreSDK16ChangeAgencyView")
@interface ChangeAgencyView : UIView
@property (nonatomic, readonly, strong) UILabel * _Nonnull orgLabel;
@property (nonatomic, readonly, strong) UIButton * _Nonnull changeAgencyButton;
@property (nonatomic, copy) void (^ _Nullable changeAgency)(void);
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nonnull instancetype)init;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)setEmpty;
@end

SWIFT_CLASS("_TtC10BMTCoreSDK15ChildOrgUrlUtil")
@interface ChildOrgUrlUtil : NSObject
+ (NSString * _Nonnull)checkAndUpdateEndPointWithEndPoint:(NSString * _Nonnull)endPoint SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)checkAndUpdateEndPointWithOrgUuidWithEndPoint:(NSString * _Nonnull)endPoint SWIFT_WARN_UNUSED_RESULT;
+ (NSDictionary<NSString *, id> * _Nullable)getChildOrgDict SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC10BMTCoreSDK14ControllerUtil")
@interface ControllerUtil : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIViewController * _Nullable topViewController;)
+ (UIViewController * _Nullable)topViewController SWIFT_WARN_UNUSED_RESULT;
+ (UIViewController * _Nullable)topViewControllerWithRootViewController:(UIViewController * _Nullable)rootViewController SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum DataStoreType : NSInteger;
@class NSPredicate;
SWIFT_CLASS("_TtC10BMTCoreSDK10DBCreation")
@interface DBCreation : NSObject
- (nonnull instancetype)initWithTypeOfDataStore:(enum DataStoreType)typeOfDataStore OBJC_DESIGNATED_INITIALIZER;
- (void)createDataBaseWithName:(NSString * _Nonnull)name success:(SWIFT_NOESCAPE void (^ _Nonnull)(void))success failure:(SWIFT_NOESCAPE void (^ _Nonnull)(NSError * _Nonnull))failure;
- (void)createTableWithName:(NSString * _Nonnull)name parameters:(NSDictionary<NSString *, id> * _Nonnull)parameters success:(SWIFT_NOESCAPE void (^ _Nonnull)(void))success failure:(SWIFT_NOESCAPE void (^ _Nonnull)(NSError * _Nonnull))failure;
- (void)insertDataIntoTableWithName:(NSString * _Nonnull)name parameters:(NSDictionary<NSString *, id> * _Nonnull)parameters successCompletionHandler:(SWIFT_NOESCAPE void (^ _Nonnull)(void))successCompletionHandler failureCompletionHandler:(SWIFT_NOESCAPE void (^ _Nonnull)(NSError * _Nonnull))failureCompletionHandler;
- (void)updateDataIntoTableWithName:(NSString * _Nonnull)name parameters:(NSDictionary<NSString *, id> * _Nonnull)parameters predicate:(NSPredicate * _Nullable)predicate successCompletionHandler:(SWIFT_NOESCAPE void (^ _Nonnull)(void))successCompletionHandler failureCompletionHandler:(SWIFT_NOESCAPE void (^ _Nonnull)(NSError * _Nonnull))failureCompletionHandler;
- (void)fetchDataFromTableWithName:(NSString * _Nonnull)name key:(NSString * _Nonnull)key predicate:(NSPredicate * _Nullable)predicate successWithDataCompletionHandler:(SWIFT_NOESCAPE void (^ _Nonnull)(BOOL, NSDictionary<NSString *, id> * _Nullable))successWithDataCompletionHandler failureCompletionHandler:(SWIFT_NOESCAPE void (^ _Nonnull)(NSError * _Nonnull))failureCompletionHandler;
- (void)deleteDataFromTableWithName:(NSString * _Nonnull)name predicate:(NSPredicate * _Nullable)predicate successCompletionHandler:(SWIFT_NOESCAPE void (^ _Nonnull)(void))successCompletionHandler failureCompletionHandler:(SWIFT_NOESCAPE void (^ _Nonnull)(NSError * _Nonnull))failureCompletionHandler;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// This enum will give capability to change data store type
typedef SWIFT_ENUM(NSInteger, DataStoreType, open) {
  DataStoreTypeCoreData = 0,
  DataStoreTypeSqlite = 1,
};

typedef SWIFT_ENUM(NSInteger, DateFormat, open) {
  DateFormatISO8601 = 0,
};

@interface NSDateFormatter (SWIFT_EXTENSION(BMTCoreSDK))
+ (NSString * _Nonnull)dateStringWithCurrentLocaleFromDate:(NSDate * _Nonnull)date SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)timeStringWithCurrentLocaleFromDate:(NSDate * _Nonnull)date SWIFT_WARN_UNUSED_RESULT;
@end

typedef SWIFT_ENUM(NSInteger, FontSize, open) {
  FontSizeSmall6 = 6,
  FontSizeSmall7 = 7,
  FontSizeSmall8 = 8,
  FontSizeSmall9 = 9,
  FontSizeSmall10 = 10,
  FontSizeSmall11 = 11,
  FontSizeSmall12 = 12,
  FontSizeMedium13 = 13,
  FontSizeMedium14 = 14,
  FontSizeMedium15 = 15,
  FontSizeMedium16 = 16,
  FontSizeLarge17 = 17,
  FontSizeLarge19 = 19,
  FontSizeLarge21 = 21,
  FontSizeLarge23 = 23,
  FontSizeLarge25 = 25,
};

enum NetworkReachabilityStatus : NSInteger;
SWIFT_CLASS("_TtC10BMTCoreSDK26NetworkReachabilityManager")
@interface NetworkReachabilityManager : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NetworkReachabilityManager * _Nonnull shared;)
+ (NetworkReachabilityManager * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, copy) void (^ _Nullable reachabilityStatusChangeBlock)(enum NetworkReachabilityStatus);
@property (nonatomic, readonly) BOOL isReachable;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (void)startMonitoring;
@end

typedef SWIFT_ENUM(NSInteger, NetworkReachabilityStatus, open) {
  NetworkReachabilityStatusUnknown = -1,
  NetworkReachabilityStatusNotReachable = 0,
  NetworkReachabilityStatusReachableViaCellular = 1,
  NetworkReachabilityStatusReachableViaWiFi = 2,
};

SWIFT_CLASS("_TtC10BMTCoreSDK27NotificationDatabaseManager")
@interface NotificationDatabaseManager : NSObject
- (void)updateNotificationsWithNotification:(BMNotification * _Nonnull)notification;
- (void)checkAndUpdateRemoteNotificationsWithNotifications:(NSArray<BMNotification *> * _Nonnull)notifications completion:(NotificationListCompletion _Nullable)completion;
- (void)insertNotificationsWithNotifications:(NSArray<BMNotification *> * _Nonnull)notifications completion:(NotificationListCompletion _Nullable)completion;
- (void)fetchNotificationsWithCompletion:(NotificationListCompletion _Nullable)completion;
- (void)deleteNotifications;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC10BMTCoreSDK9OrgConfig")
@interface OrgConfig : NSObject
+ (id _Nullable)getOrgConfigWith:(NSString * _Nonnull)orgId key:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC10BMTCoreSDK31OrganizationConfigurationParser")
@interface OrganizationConfigurationParser : BMNetworkResponseParser
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC10BMTCoreSDK13PassKitHelper")
@interface PassKitHelper : NSObject
+ (void)suppressApplePay;
+ (void)enableApplePay;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC10BMTCoreSDK11StringUtils")
@interface StringUtils : NSObject
+ (NSString * _Nullable)firstDigitsFrom:(NSInteger)inputDigits input:(NSString * _Nullable)input SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nullable)lastDigitsFrom:(NSInteger)inputDigits input:(NSString * _Nullable)input SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIWindow;
@interface UIApplication (SWIFT_EXTENSION(BMTCoreSDK))
- (UIWindow * _Nullable)currentUIWindow SWIFT_WARN_UNUSED_RESULT;
@end

@interface UIFont (SWIFT_EXTENSION(BMTCoreSDK))
/// Use this <em>restrictFont()</em> func  for easy restriction at all times with or without textstyles
/// We are restricting max font size upto AX2
- (UIFont * _Nonnull)restrictFont SWIFT_WARN_UNUSED_RESULT;
/// In some cases where you want your own restriction , use the below scaling func <em>restrictFont(scale: )</em> for your required font restriction
/// also it will be useful for Objective C interoperability
- (UIFont * _Nonnull)restrictFontWithScale:(CGFloat)scale SWIFT_WARN_UNUSED_RESULT;
@end

@interface UILabel (SWIFT_EXTENSION(BMTCoreSDK))
- (UIFont * _Nonnull)restrictFontWithCurrentFontSize:(CGFloat)currentFontSize SWIFT_WARN_UNUSED_RESULT;
@end

@interface UITextField (SWIFT_EXTENSION(BMTCoreSDK))
- (UIFont * _Nonnull)restrictFontWithCurrentFontSize:(CGFloat)currentFontSize SWIFT_WARN_UNUSED_RESULT;
@end

@interface UITextView (SWIFT_EXTENSION(BMTCoreSDK))
- (UIFont * _Nonnull)restrictFontWithCurrentFontSize:(CGFloat)currentFontSize SWIFT_WARN_UNUSED_RESULT;
@end

@interface UIView (SWIFT_EXTENSION(BMTCoreSDK))
- (CGFloat)getCurrentBodyStyleFontSize SWIFT_WARN_UNUSED_RESULT;
@end

@interface UIViewController (SWIFT_EXTENSION(BMTCoreSDK))
@property (nonatomic, readonly, strong) UIViewController * _Nullable previousViewController;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
