//
//  BMWLPaymentAssets.h
//  BMWhiteLabelSDK
//
//  Created by Kevin Rejko on 1/4/18.
//  Copyright © 2018 Bytemark, Inc.. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//

#import <UIKit/UIKit.h>



@interface UIColor (BMWLPaymentAssetsAdditions)

- (UIColor*)blendedColorWithFraction: (CGFloat)fraction ofColor: (UIColor*)color;

@end



typedef enum : NSInteger
{
    BMWLPaymentAssetsResizingBehaviorAspectFit, //!< The content is proportionally resized to fit into the target rectangle.
    BMWLPaymentAssetsResizingBehaviorAspectFill, //!< The content is proportionally resized to completely fill the target rectangle.
    BMWLPaymentAssetsResizingBehaviorStretch, //!< The content is stretched to match the entire target rectangle.
    BMWLPaymentAssetsResizingBehaviorCenter, //!< The content is centered in the target rectangle, but it is NOT resized.

} BMWLPaymentAssetsResizingBehavior;

extern CGRect BMWLPaymentAssetsResizingBehaviorApply(BMWLPaymentAssetsResizingBehavior behavior, CGRect rect, CGRect target);


@interface BMWLPaymentAssets : NSObject

// iOS Controls Customization Outlets
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* idealPaymentMethodTargets;

// Colors
+ (UIColor*)gradientColor;
+ (UIColor*)gradientColor2;

// Gradients
+ (CGGradientRef)visaCardGradient;

// Drawing Methods
+ (void)drawAmericanExpressPaymentMarkWithFrame: (CGRect)frame;
+ (void)drawBankPaymentMarkWithFrame: (CGRect)frame;
+ (void)drawDinersClubPaymentMarkWithFrame: (CGRect)frame;
+ (void)drawDiscoverPaymentMarkWithFrame: (CGRect)frame;
+ (void)drawDefaultPaymentMarkWithFrame: (CGRect)frame;
+ (void)drawJCBPaymentMarkWithFrame: (CGRect)frame;
+ (void)drawMasterCardPaymentMarkWithFrame: (CGRect)frame;
+ (void)drawVisaPaymentMarkWithFrame: (CGRect)frame;
+ (void)drawPayPalPaymentMarkWithFrame: (CGRect)frame;
+ (void)drawApplePayPaymentMarkWithFrame: (CGRect)frame;
+ (void)drawIdealPaymentMethod;
+ (void)drawIdealPaymentMethodWithFrame: (CGRect)targetFrame resizing: (BMWLPaymentAssetsResizingBehavior)resizing;
+ (void)drawVisaCardWithFrame: (CGRect)frame;
+ (void)drawMasterCardCardWithFrame: (CGRect)frame;
+ (void)drawAmericanExpressCardWithFrame: (CGRect)frame;
+ (void)drawJCBCardWithFrame: (CGRect)frame;
+ (void)drawDinersClubCardWithFrame: (CGRect)frame;
+ (void)drawDiscoverCardWithFrame: (CGRect)frame;
+ (void)drawDefaultCardWithFrame: (CGRect)frame;

// Generated Images
+ (UIImage*)imageOfAmericanExpressPaymentMarkWithSize: (CGSize)imageSize;
+ (UIImage*)imageOfBankPaymentMarkWithSize: (CGSize)imageSize;
+ (UIImage*)imageOfDinersClubPaymentMarkWithSize: (CGSize)imageSize;
+ (UIImage*)imageOfDiscoverPaymentMarkWithSize: (CGSize)imageSize;
+ (UIImage*)imageOfDefaultPaymentMarkWithSize: (CGSize)imageSize;
+ (UIImage*)imageOfJCBPaymentMarkWithSize: (CGSize)imageSize;
+ (UIImage*)imageOfMasterCardPaymentMarkWithSize: (CGSize)imageSize;
+ (UIImage*)imageOfVisaPaymentMarkWithSize: (CGSize)imageSize;
+ (UIImage*)imageOfPayPalPaymentMarkWithSize: (CGSize)imageSize;
+ (UIImage*)imageOfApplePayPaymentMarkWithSize: (CGSize)imageSize;
+ (UIImage*)imageOfIdealPaymentMethod;
+ (UIImage*)imageOfVisaCardWithSize: (CGSize)imageSize;
+ (UIImage*)imageOfMasterCardCardWithSize: (CGSize)imageSize;
+ (UIImage*)imageOfAmericanExpressCardWithSize: (CGSize)imageSize;
+ (UIImage*)imageOfJCBCardWithSize: (CGSize)imageSize;
+ (UIImage*)imageOfDinersClubCardWithSize: (CGSize)imageSize;
+ (UIImage*)imageOfDiscoverCardWithSize: (CGSize)imageSize;
+ (UIImage*)imageOfDefaultCardWithSize: (CGSize)imageSize;

@end
